---
eget_packages:
  - astro
  - backlog
  - bat
  - btop
  - bun
  - claude
  - duf
  - eza
  - fd
  - glow
  - jq
  - micromamba
  - nono
  - opencode
  - pandoc
  - rg
  - rga
  - tealdeer
  - vale
  - vopono
  - yq
